config/routes.rb
MyNotes::Application.routes.draw do
  
  devise_for :users

  resources :notes do
    collection do
      get 'public_notes'
      get 'public_notes_image'
      get 'free_download'
    end
  end

  post 'search', to: 'notes#search', as: :search

  resources :home

  root :to => 'home#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  before_create :randomize_file_name
  #developer@yopmail.com / 11111111
  #attr_accessor :notes_avatar_file_name, :mynotes_file_file_name, :notes_avatar
  attr_accessible :title, :description, :price, :mynotes_file, :publish, :author, :notes_avatar, :user_id, :notes_type_id
  
 # attr_accessor :check_format
   belongs_to :user

   has_attached_file :mynotes_file,
	:storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :unique_filename => false
    }

   has_attached_file :notes_avatar,
    :storage => :dropbox,
    :styles => { :small => "150x150>", :medium => "300x300>", :large => "600x600>" },
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :unique_filename => false
    }

    validates_format_of :mynotes_file_file_name, :message => "Accept only pdf", :with => %r{\.(pdf)$}i
    validates_attachment_content_type :notes_avatar, :content_type => ['image/jpeg', 'image/png','image/jpg'],:message=>"file type is not allowed (only jpeg/png/gif images)"

    validates :title, :price, :description, :author, :notes_avatar ,:presence => true
    validates_attachment_size :mynotes_file, :less_than => 5.megabytes, :message=> "size less than 1 MB"
    validates_attachment_size :notes_avatar, :less_than => 200.kilobytes, :message=> "size less than 200 KB"

    validates :description, length: { in: 50..500 }, :if => :description_is_blank?

    scope :free_notes, lambda { where("price = ? and publish = ?", 0, true)}
    scope :chargeable_notes, lambda { where("price != ? and publish=?", 0, true)}
    scope :search, lambda{|q| where("lower(title) like ? or lower(description) like ? or lower(author) like ? or notes_type_id in (?)", q.downcase, q.downcase, q.downcase, NotesType.where('lower(name) like ?', q.downcase).map(&:id))}

  def description_is_blank?
    !!self.description
  end

  def self.search_result(q, is_free)
    res = search(q)
    is_free ? res.delete_if{|b| b.price > 0} : res
  end

  def self.decoding_notes_id(notes_id)
     Base64.decode64(notes_id.to_s)
  end

 private

  def randomize_file_name
    unless mynotes_file_file_name.nil?
      extension = File.extname(mynotes_file_file_name).downcase
      self.mynotes_file.instance_write(:file_name, "#{Time.now.to_i.to_s}#{extension}")
    end

    unless notes_avatar_file_name.nil?
      extension = File.extname(notes_avatar_file_name).downcase
      self.notes_avatar.instance_write(:file_name, "#{Time.now.to_i.to_s}#{extension}")
    end
  end

end

app/models/notes_type.rb
class NotesType < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :mobile, :role
  # attr_accessible :title, :body

  has_many :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  require "base64"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home
		redirect_to public_notes_notes_path
	end

	def index
		redirect_to public_notes_notes_path
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!, :only=>[:index,:new,:create]

  def index
  end

  def new
  	@notes = Note.new
  end

  def create
    debugger
  	@notes = current_user.notes.build(params[:note])
  	if @notes.valid?
  	  @notes.save
  	  redirect_to new_note_path, :notice=>"Your notes is succefully created"
  	else
  	  render :new
  	end
  end

  def show
    @note = Note.find(params[:id].to_i)
  end

  def public_notes
    @public_notes = Note.free_notes
    @chargeable_notes = Note.chargeable_notes.order("price")
  end

  def public_notes_image
    notes = Note.find(params["public_notes"].to_i)
    render :partial=>"notes/image_load", :locals => { :public_notes => notes.notes_avatar.url(:medium), :show_notes=>notes.id }
  end

  def free_download
    notes = Note.find(Note.decoding_notes_id(params["public_notes"]).to_i)
    download_url = notes.mynotes_file.url(:download => true)
    render :partial=>"free_download", :locals => { :download_url => download_url }
  end

  def search
    is_search_for_free_notes = params[:q].downcase.include? "free"
    if is_search_for_free_notes
      splited_text = params[:q].split(" ")
      index = splited_text.each_index.select{|i| splited_text[i] == 'free'}
      splited_text.delete_at(index.first)
      params[:q] = splited_text.join(" ")
    end
    query = "%#{params[:q]}%"
    @notes = Note.search_result(query, is_search_for_free_notes)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	def truncate_text(text,size=50)
		truncate text, length: size
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
	def publish_option_list
    options=""
    [true,false].each do |index|
      options+="<option value=#{index}>#{index}</option>"
    end
    options.html_safe
  end

  def encoding_notes_id(notes_id)
  	Base64.encode64(notes_id.to_s)
  end

end

app/helpers/users_helper.rb
module UsersHelper

	def role_list
    options=""
    ["Writer","Reader"].each do |index|
      options+="<option value=#{index}>#{index}</option>"
    end
    options.html_safe
  end

end

app/views/home/home.html.erb
<%= image_tag("Website_Under_Construction.gif") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNotes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial=>"shared/menu" %>  
  <%#= render :partial=>"shared/slide" %>
  <div class="content">
  <%= render :partial=>"shared/flash_msg" %>
  <%= render :partial=>"shared/search_ebook" %>
  <%= yield %>
  </div>

  <%= render partial:"shared/footer" %>
 
</body>
</html>

app/views/notes/_download_modal.html.erb
  <!-- Modal -->
  <div class="modal fade" id="download_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">Thios i istetse
          <div class="response-content">This is </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

<script>
  $(document).ready(function(){
    $(".free_download").on("click",function(){
      $(".ajax_loader_image").show();
      var public_notes = $(this).attr("public_notes_id");
      $.ajax({
        type: "GET",
        url: "/notes/free_download",
        data: {public_notes:public_notes },
        success: function(data){
          $(".ajax_loader_image").hide();
          $(".modal-body").html(data);
          $('#download_modal').modal('show');
        },
        error: function (response) {
          $(".ajax_loader_image").hide();
          $(".modal-body").html("Something happen wrong please try again");
          $('#download_modal').modal('show');
        }
      });
    });
  });
</script>

app/views/notes/_free_download.html.erb
If download not started then <%= link_to "click here", download_url, :class=>"downloading_notes_from_url" %>

<script>
 $(document).ready(function(){
 	window.open($(".downloading_notes_from_url").attr("href"));
 	$(".downloading_notes_from_url").on("click",function(){
		$(".modal-body").empty();
		$('#download_modal').modal('hide')
 	});
 });
</script>

app/views/notes/_image_load.html.erb
<%=link_to image_tag(public_notes, height: "150px", width: "150px",:class=>"public_notes_image"), note_path(show_notes) %>

app/views/notes/_notes.html.erb
<div class="ajax_loader_image"></div>
<div class="container-fluid">
  <div class="row-fluid">
    
    <div class="span3">
      This is vijay
    </div>

    <div class="span8">
      <div class="public_notes_container">
        <h4 class="muted text-center">Search Results</h4>
        <!-- <abbr title="attribute">attr</abbr> -->
        <%@notes.each do |note|%>
          <div class="row-fluid border-below", style="margin-left:20px;">

            <div style="width:160px;" class="span3 image_loading_ajax" id="<%= note.id %>" >
                <div class="image_ajax_loader">
                    <div class="loading_image_please_wait"><%= image_tag("loading_image.gif", :height=>"150px") %>
                    </div>
                </div>
            </div>
            <div class="span8">
                <div class="row"><h4><%= truncate_text(note.title) %> </h4></div>
                <div class="row"><%= note.author %> </div>
                <div class="row" style="margin-top: 9px; width: 54%;"><%= truncate_text(note.description,70) %> </div>
                <div class="row" style="margin-top: 9px;">
                    <div class="green_font pull-left">RS <%= note.price %> /- </div>
                    <div class="pull-right"> <%= link_to "#" ,:class=>"btn btn-success btn-small free_download",:public_notes_id=>encoding_notes_id(note.id) do%>
                        <i class="icon-white icon-book"></i> Download! <%end%>
                    </div>
                </div>
            </div>
          </div>
        <%end%>

      </div>
    </div>
  </div>
</div>

app/views/notes/_public_notes_image.html.erb
<%= javascript_tag do -%>
  $(window).load(function(){
    $(".image_loading_ajax").each(function() {
      var pnotes = $(this).attr("id");
      $.ajax({
      type: "GET",
      async: true,
      url: "/notes/public_notes_image",
        data: {public_notes:pnotes },
        success: function(data){
          $("#"+pnotes+" .image_ajax_loader").empty();
          $("#"+pnotes).html(data)
        }
      });
    });
  });
<% end %>

app/views/notes/new.html.erb
<div class="container">
    <div id="login-wraper">
        <% if @notes.errors.any? %>
            <div class="alert alert-error">
                <button class="close" data-dismiss="alert">×</button>
                <% @notes.errors.full_messages.each do |msg| %>
                    <p><%= msg %></p>
                <% end %>
            </div>
        <%end%>
        <%= form_for @notes,:url => notes_path, :html => { :multipart => true } do |f| %>
            <legend>Upload Notes</legend>
        
            <div class="body">
              <div class="control-group control-inline">
                  <%= f.label :title %>
                  <%= f.text_field :title, :autofocus => true %>
              </div>

              <div class="control-group control-inline">
                  <%= f.label :description %>
                  <%= f.text_area :description,:rows=>5, :cols=>40 %>
              </div>

              <div class="control-group control-inline">
                  <%= f.label :author %>
                  <%= f.text_field :author %>
              </div>

              <div class="control-group control-inline">
                  <%= f.label :notes_type %>
                  
                  <%= f.select("notes_type_id", NotesType.all.collect {|p| [ p.name, p.id ]}) %>
              </div>

              <div class="control-group control-inline">
                  <%= f.label :publish %>
                  <%= f.select :publish, options_for_select([["Yes",true],["No",false]]) %>
              </div>

              <div class="control-group control-inline">
                  <%= f.label :price %>
                  <%= f.text_field :price %>
              </div>
              
              <div class="control-group control-inline">
                  <%= label_tag 'Cover Image' %><h6> (<%= t(:text)[:cover_image_size] %>)</h6>
                  <%= f.file_field :notes_avatar %>
              </div>
              </br>

              <div class="control-group control-inline">
                  <%= label_tag 'Upload Notes' %> <h6>(<%= t(:text)[:upload_file_size] %>)</h6>
                  <%= f.file_field :mynotes_file %>
              </div>

            </div>
        </br></br>
            <div class="login-footer">
              <%= f.submit "Upload", :class=>"btn-large btn-success" %>
            </div>
        
        <%end%>
    </div>

</div>

<div>
      <%# @my_notes.each do |my_notes|%>
       <%#=link_to "download", my_notes.mynotes_file.url(:download => true) %>
    <%#end%>
</div>

app/views/notes/public_notes.html.erb
<div class="ajax_loader_image"></div>
<div class="container-fluid">
  <div class="row-fluid">
    
    <div class="span3">
      This is vijay
    </div>
    
    <div class="span8">
      <div class="public_notes_container">
        <h4 class="muted text-center">Free download Notes</h4>
        <div id="myCarousel" class="carousel slide row-fluid"> 
          <div class="carousel-inner">
            <div class="item active offset1">
              <% @public_notes.each_with_index do |public_notes,index| %>
                <%if (index)%4==0 and index!=0%>
                  </div><div class="item offset1">    
                <%end%>
                  <div class="row-fluid span3">
                    <div class="image_loading_ajax" id="<%= public_notes.id %>" >
                      <div class="image_ajax_loader"><div class="loading_image_please_wait"><%= image_tag("loading_image.gif", :height=>"150px") %></div>
                      </div>
                    </div>
                    <%#public_notes.mynotes_file.url(:download => true)%>
                    <div style="margin-top:10px;"><%= truncate public_notes.title, length: 50 %> </div>
                    <div style="margin-top:10px;"><%= link_to "#" ,:class=>"btn btn-success btn-small free_download",:public_notes_id=>encoding_notes_id(public_notes.id) do%>
                      <i class="icon-white icon-book"></i> Download! <%end%>
                    </div>
                  </div>
              <%end%>  
            </div>
          </div>
          <!-- Carousel nav -->  
          <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>  
          <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a> 
        </div>
      </div>

      <div class="public_notes_container">
        <h4 class="text-center"><span class="muted cross_line">Purchase and Download Notes</span><span class="offer"><b style="color:blue !important"> Offer</b> Free download notes</span><%=image_tag "offer.gif" %></h4>
        <div id="purhaseCarousel" class="carousel slide row-fluid"> 
          <div class="carousel-inner">
            <div class="item active offset1">
              <%if @chargeable_notes.blank? %><h3 class="muted text-center">No Notes is available</h3> <%end%>
              <% @chargeable_notes.each_with_index do |chargeable_note, index| %>
                <%if (index)%4==0 and index!=0%>
                  </div><div class="item offset1">    
                <%end%>
                <div class="row-fluid span3">
                  <div class="image_loading_ajax" id="<%= chargeable_note.id %>" >
                    <div class="image_ajax_loader">
                      <div class="loading_image_please_wait"><%= image_tag("loading_image.gif", :height=>"150px") %>
                      </div>
                    </div>
                  </div>
                  <div class="green_font margin-top-row-notes-price">RS <%=chargeable_note.price %> /-</div>
                  <div style="margin-top:10px;"><%= truncate chargeable_note.title, length: 50 %> </div>
                  <div style="margin-top:10px;"><a href="#" class="btn btn-success btn-small"><i class="icon-white icon-book"></i> Buy!</a></div>
                  </div>
              <%end%>  
            </div>
          </div>
          <!-- Carousel nav -->  
          <a class="carousel-control left" href="#purhaseCarousel" data-slide="prev">‹</a>  
          <a class="carousel-control right" href="#purhaseCarousel" data-slide="next">›</a> 
        </div>
      </div>

    </div>
      
  <%= render :partial=>"notes/public_notes_image" %>
  </div>
</div>
<%= render :partial=>"notes/download_modal" %>

app/views/notes/search.html.erb
<%= render :partial=> "notes"%>
<%= render :partial=>"notes/public_notes_image" %>
<%= render :partial=>"notes/download_modal" %>

app/views/notes/show.html.erb
<%= @note.description %>

app/views/shared/_after_login_menu.html.erb
<li class="dropdown">
	<%= link_to "Javascript:void(0);", :class=>"dropdown-toggle", "data-toggle"=>"dropdown" do %>
		<%= current_user.full_name %> <b class="caret"></b>
	<%end%>    

	<ul class="dropdown-menu">
  		<li><%= link_to "Logout", destroy_user_session_path, :method=>"delete" %></li>
	</ul>
</li>

<li class="dropdown">
	<%= link_to "Javascript:void(0);", :class=>"dropdown-toggle", "data-toggle"=>"dropdown" do %>
		My Notes <b class="caret"></b>
	<%end%>    

	<ul class="dropdown-menu">
  		<li><%= link_to "Upload My Notes", new_note_path %></li>
  		<li><%= link_to "Uploaded", notes_path %></li>
	</ul>
</li>

app/views/shared/_flash_msg.html.erb
<div id="flash">
	<% flash.each do |type, message| %>
		<div class="alert fade in text-center">
		  <button class="close" data-dismiss="alert">×</button>
		  <%= message.html_safe %>
		</div>
	<% end %>

</div>

app/views/shared/_footer.html.erb
<footer id="footer" class="vspace20">
	<div class="container">
		<div class="row">
			<div class="span4">
				<h4>About Us</h4>
				<blockquote>This is a set of free responsive template free to download and to use to create your own website.<br />
					The package contains varius tipologies of layouts.
				</blockquote>
			</div> 
	
			<div class="span4">
				<h4>Location and Contacts</h4>
				<p><i class="icon-map-marker"></i>&nbsp;Vijay chouhan</p>
				<p><i class="icon-phone"></i>&nbsp;Phone: 09827438634</p>
				<p><i class="icon-print"></i>&nbsp;Not available</p>
				<p><i class="icon-envelope"></i>&nbsp;Email: vijaychouhan@programmer.net</p>
				<p><i class="icon-globe"></i>&nbsp;Web: http://www.vijaychouhan.in</p>
			</div>
			
			<div class="span4">
				<h4>Newsletter</h4>
				<p>Write you email to subscribe to our Newsletter service. Thanks!</p>
				<form class="form-newsletter">
				  <div class="input-append">
				    <input type="email" class="span2" placeholder="your email">
				    <button type="submit" class="btn">Subscribe</button>
				  </div>
				</form>
				
				<h4>Follow Us on Socials</h4>
				<p>
					<a href="#"><img src="img/socials/facebook.png" alt="" /></a>
					<a href="#"><img src="img/socials/twitter.png" alt="" /></a>
					<a href="#"><img src="img/socials/youtube.png" alt="" /></a>
				</p>
			</div>
		</div>
		
		<div class="row">
			<div class="span6">
				<p>&copy;<a href="#">Privacy</a>&nbsp;&amp;&nbsp;<a href="#">Terms and Conditions</a></p>
			</div>
			<div class="span2 offset4">
				<a href="http://www.vijaychouhan.in" target="_blank">credits by Responsive Web Mobile</a>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_menu.html.erb
<div class="navbar navbar-inverse navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" href="#">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "MyNotes.com", home_index_path,:class=>"brand" %>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Homepages <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid1a.html">homepage A</a></li>
							<li><a href="grid1b.html">homepage B</a></li>
							<li><a href="grid1c.html">homepage C</a></li>
							<li><a href="grid1d.html">homepage D</a></li>
							<li><a href="grid1e.html">homepage E</a></li>
							<li><a href="grid1f.html">homepage F</a></li>
							<li><a href="grid1g.html">homepage G</a></li>
							<li><a href="grid1h.html">homepage H</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Blogs <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid2a.html">Blog A</a></li>
							<li><a href="grid2b.html">Blog B</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Shop <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid5a.html">Shop A</a></li>
							<li><a href="grid5b.html">Shop B</a></li>
							<li><a href="grid5c.html">Shop C</a></li>
							<li><a href="grid5d.html">Shop D</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid9a.html">Portfolio Isotope A</a></li>
							<li><a href="grid9b.html">Portfolio Pinterest Isotope B</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Pricing <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid10a.html">Pricing A</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Various <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid4a.html">Various A</a></li>
							<li><a href="grid4b.html">Various B</a></li>
						</ul>
					</li>
					<% unless signed_in? %>
						<li class="dropdown">
								<%= link_to "Login", new_user_session_path %>
						</li>
						<li class="dropdown">
							<%= link_to "Registration", new_user_registration_path %>
						</li>
					<%else%>
						<%= render :partial=>"shared/after_login_menu" %>
					<% end %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="grid8a.html">Contact A</a></li>
							<li><a href="grid8b.html">Contact B</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/shared/_search_ebook.html.erb
<div class="row-fluid">
	<nav id="search">
                <%= form_tag search_path do %>
                    <label for="search_input">Find the book you need</label>
                    <input type="search" required="" data-autocomplete="/services/en/autocomplete" placeholder="Search for a book" name="q" id="search_input" autocomplete="off" class="acInput">
                    <button type="submit">Go!</button>
                <%end%>
            </nav>
</div>

app/views/shared/_signup.html.erb
<div class="container">
		<div class="row">

			<div class="span6">

				<div class="register-info-wraper">
					<div id="register-info">

						<h1>Use the Form behind for FREE Registration</h1>

						<ul>
							<li>It's Free</li>
							<li>What are you waiting for?</li>
							<li>Are you still reading?</li>
							<li>Move on!</li>
						</ul>

					</div>
				</div>

			</div>

			<div class="span6">
				<div id="wraper">
					<form id="register-form" class="form">
						<legend>Register</legend>

						<div class="body">
							<!-- first name -->
							<div class="control-group control-inline">
								<label for="name">First name</label>
								<input name="name" class="input-medium" type="text">
							</div>
							<!-- last name -->
							<div class="control-group control-inline">
								<label for="surname">Last name</label>
								<input name="surname" class="input-medium" type="text">
							</div>
							<!-- username -->
							<label>Username</label>
							<input class="input-huge" type="text">
							<!-- email -->
							<label>E-mail</label>
							<input class="input-huge" type="text">
							<!-- password -->
							<label>Password</label>
							<input class="input-huge" type="text">

						</div>

						<div class="footer">
							<label class="checkbox inline">
								<input type="checkbox" id="inlineCheckbox1" value="option1"> I agree but I will never read this
							</label>
							<br />
							<button type="submit" class="btn btn-success">Register</button>
						</div>
					</form>
				</div>
			</div>

		</div>
	</div>

app/views/shared/_slide.html.erb
<!-- <div id="carousel" class="">		
	<div id="myCarousel" class="carousel slide mbottom0">
	  <div class="carousel-inner">
	    <div class="active item">
	    	<%= image_tag "slide/slide-01.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Another example of Responsive Web Template.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
				</div>
			</div>
	    </div>
			
	    <div class="item">
	    	<%= image_tag "slide/slide-02.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Another example of Responsive Web Template.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
				</div>
			</div>
	    </div>
	
	    <div class="item">
	    	<%= image_tag "slide/slide-03.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Another example of Responsive Web Template.</h1>
					<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
				</div>
			</div>
	    </div>
	  </div>
	  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
</div>
 -->